name: Update blog

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/blog.yml
      - blog/**/*

env:
  ADDRESS: ${{ vars.OMG_LOL_NAME }}
  API_KEY: ${{ secrets.OMG_LOL_API_KEY }}

jobs:
  weblog_import:
    runs-on: ubuntu-latest
    name: weblog.lol
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: weblog_import
        uses: neatnik/weblog.lol@v1
        env:
          ADDRESS: ${{ secrets.OMG_LOL_ACCT_EMAIL }}
          WEBLOG_API_KEY: ${{ secrets.OMG_LOL_API_KEY }}