name: Update Now Page

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/now.yml
      - now/*

env:
  ADDRESS: ${{ vars.OMG_LOL_NAME }}
  API_KEY: ${{ secrets.OMG_LOL_API_KEY }}

jobs:
  web_import:
    runs-on: ubuntu-latest
    name: ${{ vars.OMG_LOL_NAME }}.omg.lol/now
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: install jq
        run: sudo apt install jq
      - name: create payload and post to api
        run: |
          echo '{"listed": "1","content": ""}' | jq -r --arg CONTENT "$(cat now/now.md)" '.content = $CONTENT' > payload.json
          cat payload.json
          curl --location \
            --request POST \
            --header "Authorization: Bearer ${API_KEY}" \
            "https://api.omg.lol/address/${ADDRESS}/now" \
            --data-binary "@payload.json"

            