name: Update Web Profile Page

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/web.yml
      - web/*

env:
  ADDRESS: ${{ vars.OMG_LOL_NAME }}
  API_KEY: ${{ secrets.OMG_LOL_API_KEY }}

jobs:
  web_import:
    runs-on: ubuntu-latest
    name: ${{ vars.OMG_LOL_NAME }}.omg.lol
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: create payload and post to api
        run: |
          curl --location \
            --request POST \
            --header "Authorization: Bearer ${API_KEY}" \
            "https://api.omg.lol/address/${ADDRESS}/web" \
            --data '{"publish": true, "content": "'"$(printf "%q" $(cat web/profile.md))"'"}'