name: Update Web Profile Page

on: 
  push:
    branches:
      - main
    paths:
      - .github/workflows/web.yml
      - web/*

jobs:
  web_import:
    runs-on: ubuntu-latest
    name: omg.lol
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: install jq
        run: sudo apt install jq
      - name: web_import
        env:
          ADDRESS: ${{ vars.OMG_LOL_NAME }}
          API_KEY: ${{ secrets.OMG_LOL_API_KEY }}
        run: |
          jq -r --arg CONTENT "$(cat web/profile.md)" '.content = $CONTENT' web/payload.json
          cat payload.json
          curl --location \
            --request POST \
            --header "Authorization: Bearer ${API_KEY}" \
            "https://api.omg.lol/address/${ADDRESS}/web" \
            --data-binary "@web/payload.json"